# Minimal analysis configuration for rapid development
# This is intentionally permissive to allow compilation

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "build/**"
    - "integration_test/**"
  
  errors:
    # Ignore common warnings that block CI
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    avoid_print: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
  
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Critical errors only
    - avoid_empty_else
    - avoid_returning_null_for_void
    - no_duplicate_case_values
    - throw_in_finally
    - valid_regexps
